### ISSUE TITLE
[Data API] endpoint for node sync status

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/stacks-blockchain-api#25]
Does Blockstacks API /rpc provides any information of node's syncing process ? (target height, current synced block, etc)

**Comment by diwakergupta** [comment]
> Does Blockstacks API /rpc provides any information of node's syncing process ? (target height, current synced block, etc)

The `/v2/info` endpoint contains some of this information like the current height, e.g. https://stacks-node-api.mainnet.stacks.co/v2/info

```json
{
  "peer_version": 402653184,
  "pox_consensus": "a1650a033b7bfdab7ab0f01efd91b09a26b97948",
  "burn_block_height": 671983,
  "stable_pox_consensus": "0003b0dca70405d025c56a6dd6473015c170c90f",
  "stable_burn_block_height": 671976,
  "server_version": "stacks-node 2.0.5 (master:ad14520+, release build, linux [x86_64])",
  "network_id": 1,
  "parent_network_id": 3652501241,
  "stacks_tip_height": 4838,
  "stacks_tip": "3fd9f2768437989521bfebfa5229a2b3a203c885041b3593477614b38aae0264",
  "stacks_tip_consensus_hash": "a1650a033b7bfdab7ab0f01efd91b09a26b97948",
  "genesis_chainstate_hash": "74237aa39aa50a83de11a4f53e9d3bb7d43461d1de9873f402e5453ae60bc59b",
  "unanchored_tip": "3831c059ce89caa373d39c1e5775300dd9f7c1ef4903e9c71071868259ae8a24",
  "unanchored_seq": 0,
}
```

There's no notion of a "target height" though. One option is to compare the `stacks_tip_height` of your local node with the `stacks_tip_height` of our hosted API, or one of the seed nodes e.g. http://seed-2.mainnet.stacks.co:20443/v2/info

LMK if that works, otherwise we can brainstorm other approaches.

**Comment by raynaudoe** [comment]
Thanks @diwakergupta , I'll try that approach, and let you know.

**Comment by raynaudoe** [comment]
@diwakergupta one quick question, are there any seed nodes for testnet ? 
So I can also check for `stacks_tip_height` when using testnet

**Comment by raynaudoe** [comment]
closing this.
Tracking issue on #28
